name: skygold
favicon: null
layout_spectrum: 0.09218705259263515
typography_spectrum: 0.1305061283055693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8171096039004624
  lightness: 0.4959194855764508
  saturation: 0.49371553491801023
  rhythmicContrast: 0.7886644434183836
purpose: []
